package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Wednesday, April 30, 2025 12:30:58 PM UTC
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
